#构建网站静态文件
building:
  stage: build
  image: node:18.17-alpine
  only:
    - main
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install 
    - npm run build
#生成产物上传
  artifacts:
    expire_in: 3 days
    paths:
      - build
  tags:
    - docker-1

deploying:
  stage: deploy
  only:
    - main
  script:
    - ls -l build
    - /usr/bin/ossutil64 cp -r -u build/ oss://xiebo-pro/

  tags:
    - shell