#构建网站静态文件
building:
  stage: build
  image: node:16.18-alpine
  only:
    - main
  script:
    - npm install --progress=false --no-optional
    - npm run build
#生成产物上传
  artifacts:
    expire_in: 3 days
    paths:
      - build
  tags:
    - docker-1

deploying:
  stage: deploy
  only:
    - main
  script:
    - ls build
    - ./ossutil64 ls oss://xiebo-pro

  tags:
    - shell