"""Optional maintenance step: python3 -m pip install 'fonttools[woff]==4.60.1'.

Produces small variable-font slices for the stable homepage vocabulary. Original
fonts remain available for every other glyph, so new notes never need a rebuild
of these subsets. Run again after significant homepage/poetry changes.
"""
import re
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
shared = ["src/pages/index.js", "docusaurus.config.js",
          "src/components/SiteSearchForm/index.js", "src/theme/SearchBar.js"]
ui = "".join((ROOT / name).read_text() for name in shared)
posts = []
for path in (ROOT / "blog").glob("*.md*"):
    date = re.match(r"(\d{4})-(\d{1,2})-(\d{1,2})", path.name)
    if date:
        posts.append((tuple(map(int, date.groups())), path))
recent = "".join(path.read_text().split("---")[1] for _, path in sorted(posts, reverse=True)[:3])
vocabulary = {
    "noto-sans-sc": ui + recent,
    "noto-serif-sc": ui + (ROOT / "src/pages/精选诗词表.js").read_text(),
}
source_css = (ROOT / "src/css/fonts.css").read_text()
output = ROOT / "src/fonts/home-subsets"
output.mkdir(exist_ok=True)
css = ["/* Generated by scripts/subset-home-fonts.py. Full fonts remain the fallback. */"]
total = 0
expected_files = set()
for block in re.findall(r"@font-face\s*\{[^}]+\}", source_css):
    url = re.search(r"url\(\.\./fonts/([^\)]+)\)", block)
    if not url:
        continue
    family = url[1].split("/")[0]
    if family not in vocabulary:
        continue
    original = ROOT / "src/fonts" / url[1]
    font = TTFont(original, recalcTimestamp=False)
    points = sorted(set(map(ord, vocabulary[family])) & set(font.getBestCmap()))
    # Latin remains in the original small Latin files; prioritize CJK slices.
    points = [point for point in points if point >= 0x2000]
    if not points:
        font.close()
        continue
    options = subset.Options()
    options.recalc_timestamp = False
    options.layout_features = ["*"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=points)
    subsetter.subset(font)
    destination = output / original.name
    font.flavor = "woff2"
    font.save(destination)
    font.close()
    # Verify variable weights and selected glyphs survived the transformation.
    with TTFont(destination) as verified:
        assert "fvar" in verified and set(points) <= set(verified.getBestCmap())
    expected_files.add(destination.name)
    total += destination.stat().st_size
    block = block.replace(url[1], "home-subsets/" + original.name)
    block = re.sub(r"unicode-range:[^;]+;", "unicode-range: " + ",".join(f"U+{point:X}" for point in points) + ";", block)
    css.append(block)
for path in output.glob("*.woff2"):
    if path.name not in expected_files:
        path.unlink()
(ROOT / "src/css/fonts-home.css").write_text("\n\n".join(css) + "\n")
print(f"{len(expected_files)} variable font slices, {total:,} bytes; original glyph coverage preserved")
